### PR TITLE
Fix PHP warning about undefined constants

### PR DESCRIPTION
**Pull request by andreasscherbaum**
INCLUDE_ANY is not quoted

Fix: #720

### CODE REVIEW

**Comment by onli** [comment]
Thank you for the PR!

This will fix PHP warnings and should be merged.

On the other hand, I don't think that INCLUDE_ANY does anything. It is not defined in the smarty class as far as I can see and I do not see it in the documentation. Maybe this PR could be changed to instead remove the calls linked to that undefined constant?

**Comment by andreasscherbaum** [comment]
I have no insight what the code is doing. There is similar code in other plug-ins, and then that should be removed from all plug-ins. However in most other plug-ins the code is fixed.

I only stumbled over this because it was spamming my website.

**Comment by onli** [comment]
Hm, okay. We do not need to completely remove it here.

One thing would be nice though: Could you also raise the version number of those plugins? Always the x.y.Z as Z+1. 

Without that, spartacus would not provide updates to the other users, and it's cleaner if it's in the same PR.

**Comment by andreasscherbaum** [comment]
I'm not against removing unnecessary code, quite the contrary. But I don't think I'm the right person to judge what code exactly should be removed.
I will bump the version numbers later in the evening, and update the PR.

@onli If you have a clearer picture what should be removed, can you write that into an issue?

**Comment by onli** [comment]
> @onli If you have a clearer picture what should be removed, can you write that into an issue?

I will add a comment to your issue https://github.com/s9y/Serendipity/issues/720 and maybe change the title. In general, I assume that no developer has a real overview of that setting (maybe @garvinhicking remembers?) and we just have to remove it and check if something breaks. There might be some voodoo code somewhere that does something with it that is not obvious, but I doubt it.

**Comment by andreasscherbaum** [comment]
@onli Ok, I bumbed all version numbers I found. Can you check if that's alright?

**Review by onli — COMMENTED** [review]
Almost, and that's not your fault: The plugins so far do not always follow semversion, and changes like this are a good opportunity to change that. So let's do that :) I think you should be able to simply commit these two suggestions, and then I can merge the PR.

**Comment by andreasscherbaum** [comment]
@onli Versions updated, and PR rebased.

**Comment by onli** [comment]
Und mit Dank gemerged :)

**Pull request merged**
