### PR TITLE
Add ids as link targets to spartacus web pages.

### PR DESCRIPTION
**Pull request by th-h**
It would be nice to be able to link directly to a certain plugin, so add ids to the generated HTML.

Using the plugin name should make for unique ids without illegal characters.

As I'm not really familiar with this code and have no test installation, I'd like a review before merging, please. :-)

Signed-off-by: Thomas Hochstein <thh@inter.net>

### CODE REVIEW

**Comment by onli** [comment]
I'm not familiar with the emerge_spartacus script and don't know how to test it, but the code has to work :)

**Comment by garvinhicking** [comment]
Yeah, no objections! Not sure though if we need to checkout that version of the script on our ubernauten server now. Lets see if it works automagically.

**Comment by yellowled** [comment]
Added a little something to make this even more convenient. :)

**Comment by th-h** [comment]
> Yeah, no objections! Not sure though if we need to checkout that version of the script on our ubernauten server now. Lets see if it works automagically.

It doesn't seem to work its magic ... The Spartacus site is still unchanged, as far as I can see.

**Comment by th-h** [comment]
Now SPARTACUS has picked up the change. :-)

**Pull request merged**
