### PR TITLE
Fix/801 serendipity event multilingual

### PR DESCRIPTION
**Pull request by surrim**
Fixes multilingual bugs.
Event multilingual version bumped to 2.36.1

### CODE REVIEW

**Comment by onli** [comment]
If @stephanbrunker has the time to maintain that plugin, then we should merge this or something like this. But it did not sound like the two commits picked now are properly tested, they are very big and part of a bigger rework of a fork. Just like that let's not merge this.

To get the plugin to work on PHP 8 much less is needed;

```
onli@fallout:~/additional_plugins$ diff -Nur /mnt/s9y_dev/plugins/serendipity_event_multilingual/serendipity_event_multilingual.php serendipity_event_multilingual/serendipity_event_multilingual.php
--- /mnt/s9y_dev/plugins/serendipity_event_multilingual/serendipity_event_multilingual.php	2023-02-10 17:23:39.000000000 +0100
+++ serendipity_event_multilingual/serendipity_event_multilingual.php	2023-02-10 17:14:44.617593804 +0100
@@ -27,7 +27,7 @@
             'php'         => '4.1.0'
         ));
         $propbag->add('groups',         array('FRONTEND_ENTRY_RELATED', 'BACKEND_EDITOR'));
-        $propbag->add('version',        '2.35.1');
+        $propbag->add('version',        '2.35');
         $propbag->add('configuration',  array('copytext', 'placement', 'tagged_title', 'tagged_entries', 'tagged_sidebar', 'langswitch'));
         $propbag->add('event_hooks',    array(
                 'frontend_fetchentries'     => true,
@@ -169,7 +169,7 @@
             }
         }
         if ($built == 2) {
-            $this->set_config('db_built', 3);
+           $this->set_config('db_built', 3);
         }
         if ($built == 3) {
         // OPS !!!! config set [serendipity_event_multilingual/db_built 	2] is/was build without instance ????
@@ -274,7 +274,7 @@
             return $false;
         }
 
-        foreach ($properties as $key => $value) {
+        while(list($key,) = each($properties)) {
             preg_match('@^multilingual_body_(.+)$@', $key, $match);
             if (isset($match[1])) {
                 $langs[$match[1]] = '<a class="multilingual_' . $match[1] . '" href="' . $serendipity['serendipityHTTPPath'] . $serendipity['indexFile'] . '?' . serendipity_archiveURL($id, $serendipity['languages'][$match[1]], 'serendipityHTTPPath', false) . '&amp;' . $this->urlparam($match[1]) . '">' . $serendipity['languages'][$match[1]] . '</a>';
```
The each must be removed and the non-standard SHOW INDEX (a warning which seems completely unnecessary anyway)  needs to be dropped for sqlite.

```
onli@fallout:~/additional_plugins$ diff -Nur /mnt/s9y_dev/plugins/serendipity_event_multilingual/serendipity_plugin_multilingual.php serendipity_event_multilingual/serendipity_plugin
_multilingual.php 
--- /mnt/s9y_dev/plugins/serendipity_event_multilingual/serendipity_plugin_multilingual.php	2023-02-10 17:23:30.000000000 +0100
+++ serendipity_event_multilingual/serendipity_plugin_multilingual.php	2019-02-18 17:28:13.189124994 +0100
@@ -63,7 +63,7 @@
             $conf[] = $lkey;
         }
         $propbag->add('configuration', $conf);
-        $propbag->add('version',       '1.15.1');
+        $propbag->add('version',       '1.15');
         $propbag->add('groups',        array('FRONTEND_VIEWS'));
         $this->dependencies = array('serendipity_event_multilingual' => 'remove');
     }
@@ -116,7 +116,7 @@
         $url   = serendipity_currentURL(true);
 
         echo '<form id="language_chooser" action="' . $url . '" method="post"><div>';
-        echo '<select style="font-size: ' . $this->get_config('size', '9') . 'px" name="serendipity[user_language]" onchange="document.getElementById(\'language_chooser\').submit();">';
+        echo '<select style="font-size: ' . $this->get_config('size', '9') . 'px" name="user_language" onchange="document.getElementById(\'language_chooser\').submit();">';
 //        echo '<option value=""> </option>'."\n";
         foreach ($serendipity['languages'] AS $lang_key => $language) {
             if (serendipity_db_bool($this->get_config($lang_key, 'false'))) {
```

The user_language -> serendipity[user_language] change needs to be reflected, though this is missing a switch to use user_language for old serendipity versions (we don't want to break them unnecessarily).

**Comment by stephanbrunker** [comment]
I still think we can drop all that "old s9y versions" stuff now. To get an older version running, you need a provider providing PHP7.x, which in the best case costs a huge extra. And I know no other project which is that much concerned about backward capability. As I said, Joomla 4 is mandatory, older versions aren't supported anymore and it breaks almost anything, for example. Similar for almost other software, being either Open Source or Proprietary. Update or die. I had to throw away perfectly functional hardware only because the manufacturer declared it "end of lifetime" and the USB driver wasn't compatible to Windows 7 upwards. 
Everyone who wants his system running today should update to the release version, if for safety reasons only. Supporting older versions is much like selling a tool to bypass security features. And if someone has any unsupported third-party-code on the side, I am happy to make it running for my hourly fee.
As I proposed: because of the tight interaction between the core and the multilingual plugin, I would make it part of the plugins shipped with s9y on default. It has practically no impact and can be deactivated by default.

**Comment by onli** [comment]
We don't even need to go into the ideology of it when talking about bc. There is a more practical reason: Have a look at which PHP versions are supported under the various long term supported distros. It's not PHP 8. My very own blog runs under Ubuntu 20.04.4 LTS which just does not have PHP 8 in the regular repository.

Also, it would just be rude to make a plugin incompatible for the old s9y version when that is not needed.

**Comment by onli** [comment]
> As I proposed: because of the tight interaction between the core and the multilingual plugin, I would make it part of the plugins shipped with s9y on default. 

I' not against this at all :) We'd just have to make it in a way that does not break the API unnecessarily. Like setting a default parameter when adding a new parameter, not changing the parameter order if not necessary (all of that is okay if it's broken anyway, like the ML was, but not if the functionality behind it works).

**Comment by stephanbrunker** [comment]
Unfortunately, that doesn't make sense. Hard to find a vanilla user with zero knowledge hosting his own server. And I just looked up IONOS and STRATO as the biggest ones and both as standard only provide PHP8 included, old versions cost extra, over 7€ a month which doubles the monthly regular fee. And if someone hosts his own server, he should have enough knowledge to keep his server safe which also means a supported PHP version. Otherwise it is just handing out guns to kids. I surely don't have the guts to host a server open to the internet. My own test server is only internally, runs on CENTOS7 and it is not a huge deal to get actual versions of PHP or mariaDB, both are ancient in the standard package too which causes problems by itself and interacting by phpmyadmin, so everything should be up to date.

For me it is the practical approach and my personality. I simply cannot stand patch-up jobs. So working around old code is like having a garden with dead trees and plants in it which is confusing, messy and bloated and a pain to work with later because it gets only worse over time. And if I provide the tidy new code and wait for someone else to adapt and pull it into the main repo, that is not going to happen. The subscription feature and the author and category lead pages are on my public repo for years now and nothing happened. Same was true for the multilingual plugin, back then i was told to hold it back until the 2.4 release.

And I am not going to put time and effort into something I personally don't need anymore (no much multilingual going on on my blog) and which is most probably going to be a still birth. If you want to have a gardener working in your old garden full of dead plants and is forbidden to touch that stuff, pick someone else.

I wouldn't picked up that discussion again if it hasn't surfaced itself by the means of the multilingual plugin ...

**Comment by onli** [comment]
I had an answer about bc prepared, but we should move this to a private channel - I'll send you it via mail.

Let's focus on the PR here. It's simple really: It can't be merged if it breaks the plugins in the old s9y versions (with reasonable limits, but 2.3.5 should definitely work). We can always be flexible there if there is no other way and mark the needed s9y version, but I don't see a reason to break compatibility here.

Given the discussion about it it seems like you are not interested in providing backwards compatibility in general, and well, then we won't merge it and go with a simple fix to keep things running. If that's a wrong impression I'd be very happy if you would continue working on the plugin. The needed fix could be added on top of this PR (though I don't have an overview about the compatibility of the other changes, which is exactly what I'm talking about) or be provided in a separate PR, doesn't matter.

**Comment by onli** [comment]
I had a talk with Stephan about this and came up with this plan:

 1. I will push the minimal patch so the plugin works again. Already done: https://github.com/s9y/additional_plugins/commit/4bee1b1a81cc35384f2222f0256ba18b9d89d4e2
 2. We would avoid further issues like this by moving the plugin to the core of s9y, which he suggested
 3. I would close this PR, patching the plugin like this should not be necessary anymore

Always possible to re-open if the plan is not okay :)

**Pull request closed without merging**
