### PR TITLE
dsgvo: set default of commentform checkbox to false

### PR DESCRIPTION
**Pull request by onli**
I think https://www.datenschutz-guru.de/braucht-mein-kontaktformular-jetzt-eine-checkbox/ is convincing and I remember we saw it like that as well. The checkbox should not be on by default then - this PR does that.

### CODE REVIEW

**Comment by garvinhicking** [comment]
I do not want to listen to a 15 minute podcast. Do you have a written reasoning why this is not required? All texts I have read so far indicate you do need a checkbox so that users confirm your terms of service before user submitted data is stored.

**Comment by garvinhicking** [comment]
Looks like a good idea to me!

Please remove the "checkbox" commit from this one, and please create a language constant for the "Copy to clipboard" button label, then we can commit this. However I thought that access to a browsers clipboard in many browsers doesn't work anymore?

**Comment by onli** [comment]
> Do you have a written reasoning why this is not required? 

His main point is that the dedicated approval route is the most risky, as it implies specific behaviour when approval is retracted. And he explains that there are some other ways to justify showing a comment when a comment was submitted and storing the needed metadata.

**Comment by garvinhicking** [comment]
Alright! Have a go then and commit (but please do add a language constant for that "copy to clipboard" string, I'd like to have as much as possible abstracted, I did make a few errors myself on what I hardcoded there.

**Comment by th-h** [comment]
>> Do you have a written reasoning why this is not required?
> His main point is that the dedicated approval route is the most risky, as it implies specific behaviour when approval is retracted.

That may be true, but consent (approval) is the safest way to go.

> And he explains that there are some other ways to justify showing a comment when a comment was submitted and storing the needed metadata.

I don't think that's true - he is talking about *contact* forms, not *comment* forms, in a context of contacting a contractor or service provider. That use case is very much like sending mail, and you can justify saving and storing the data as data concerning a contract or the initiation of a contract. That's out of the question for comments, obviously.

The only remaining justification besides consent is a legitimate interest of the blog owner, outweighting conflicting interest of the commenter. That's a weak and debatable justification - no need to enter that slippery slope when consent ist easy to get.

(And if we adopt the view that legitimate interest provides adequate justification, we don't need to shorten IP adresses, drop embedded fonts or CSS etc., but just argue that the blog owner has a legitimate interest to do so. I'm quite sure that's not the way to go.)

**Comment by onli** [comment]
Okay then! :)

**Pull request merged**
