### PR TITLE
Google Analytics 4 support

### PR DESCRIPTION
**Pull request by HQJaTu**
GA version 4 is the only supported version. Older versions are completely obsoleted. This adds proper support to GA4 with Google recoomended setup.

### CODE REVIEW

**Comment by garvinhicking** [comment]
Thanks so much for contributing this. This looks very solid!

However; we have a "serendipity_event_google_analytics" plugin already; would you mind to create a PR against the existing plugin and:

- use the v4 api in there instead of the outdated one
- see if some config values can be re-used
- see if some of the config values in there might also be supported in v4 and configure them too
- drop the ones that are not supported
- and of course, add yourself to the author list (you can name yourself first)
- raise the version number to a new major one, probably also raise the version requirements to s9y 2.4
- add your changelog entry there

That would be great and much appreciated, because users of the existing plugin could then see an upgrade to make it work again.

😊

**Comment by HQJaTu** [comment]
Thanks for the input. I'll need some time to process all of that and get back to you.

For me, this is the first ever attempt to craft a plugin, soi I'm not fully aware of code submission procedures.

**Comment by garvinhicking** [comment]
You did very well, and we don't really have "rules/procedures" in place. So my thoughts are just "extra".

Feel free to process this and check out if you would like to do that. I know checking the options might be tedious, just let me know and I'll try to help.

People like you are what can push open source projects forwards! 👍

**Comment by HQJaTu** [comment]
Here are my changes:
- Instead of adding a new plugin, my changes are made on top of existing (obsoleted) GA-plugin with version 2.0.0
- I'm using as much previous configuration variables as it makes sense
- Language translations are a mess, I don't have skills in DE, CS nor CS
- I made myself an author of the plugin, with full credits to author of the previous plugin
- This plugin requires S9y 2.4 and PHP 8.0
- Updated changelog

**Review by garvinhicking — APPROVED** [review]

**Comment by garvinhicking** [comment]
Awesome. Many many thanks for your rework and contribution! :-)

**Pull request merged**
