### PR TITLE
[event_geotag] onpaste event applies "lat,long" values

### PR DESCRIPTION
**Pull request by surrim**
Adds onpaste events to handle copied geodata.

Example 1 - Pasting `51.48165, 7.2164"` into lat:
- [x] lat will be `51.48165`
- [x] long will be `7.21648`

Example 2 - Pasting `12.37129 / 51.33962` into long:
- [x] long will be `12.37129`
- [x] lat will be `51.33962`

### CODE REVIEW

**Comment by garvinhicking** [comment]
Thanks a lot for your contribution! That looks very good to me. It would be perfect if your patch could also provide a bump to the plugin's version and an entry in its ChangeLog file documenting this? Then I could straight merge it. :-)

**Comment by surrim** [comment]
> Thanks a lot for your contribution! That looks very good to me. It would be perfect if your patch could also provide a bump to the plugin's version and an entry in its ChangeLog file documenting this? Then I could straight merge it. :-)

:heavy_check_mark: Done

**Comment by surrim** [comment]
> Thanks a lot for your contribution! That looks very good to me. It would be perfect if your patch could also provide a bump to the plugin's version and an entry in its ChangeLog file documenting this? Then I could straight merge it. :-)

:heavy_check_mark: Done

**Comment by garvinhicking** [comment]
Perfect! Thanks so much for this! :-)

**Pull request merged**
