### PR TITLE
New geo plugins

### PR DESCRIPTION
**Pull request by surrim**
Added 3 plugins to add interactive maps

* `event_geo_json`: to extract all entries and GPX-files from the database, inserted as `<script>const geo = {...};</script>`
* `event_osm`: to add a special `<div>` with some data-attibutes (category selection, gpx-folders, height, position, zoom) which are usefull for the static plugin
* `event_static_osm`: contain scripts and stylesheets from [openlayers](https://github.com/openlayers/openlayers) and another script to make use of the special `<div>`s.

### CODE REVIEW

**Comment by garvinhicking** [comment]
Awesome work, many thanks for sharing this. :-)

**Comment by ophian** [comment]
@surrim 
Before I merge this to Serendipity Styx https://github.com/ophian
Could you please give me a heads up for what reason is serendipity_event_static_osm.php included to serendipity_event_osm/ and how is this called? Commit https://github.com/s9y/additional_plugins/pull/109/commits/0b32070b99629174710d9001ecb1b6e0c6f09e6f#diff-b3db2557cf02c1fcbe28e8db44546417 and https://github.com/s9y/additional_plugins/pull/109/commits/dc6a58cb57089e31be4cb0317cad662935c04e07 both look alike you wanted to put this as an extra plugin but was somehow borked up.

**Comment by surrim** [comment]
> @surrim
> Before I merge this to Serendipity Styx https://github.com/ophian
> Could you please give me a heads up for what reason is serendipity_event_static_osm.php included to serendipity_event_osm/ and how is this called? Commit [0b32070#diff-b3db2557cf02c1fcbe28e8db44546417](https://github.com/s9y/additional_plugins/commit/0b32070b99629174710d9001ecb1b6e0c6f09e6f#diff-b3db2557cf02c1fcbe28e8db44546417) and [dc6a58c](https://github.com/s9y/additional_plugins/commit/dc6a58cb57089e31be4cb0317cad662935c04e07) both look alike you wanted to put this as an extra plugin but was somehow borked up.

@ophian
I put the two plugins into the same location because they depend on each other and share the same version. The main reason for splitting it into two plugins is that maps can be placed many times on a page. Static things like scripts and stylesheets are only needed once, in other words: `$propbag->add('stackable', false);`
`event_freetag`, `event_geotag`, `event_faq` and many other plugins work similarly.

**Comment by ophian** [comment]
@surrim 
Well, obviously there **is** something wrong. It (the merge to s9y plugins) hasn't even synced to the plugins xmls.
I wont touch (cleanup, convert to Styx, etc) plugins that don't even do on first commit.
Check this up with Garvin please, or your contribution has no viable value to the community.

**Comment by onli** [comment]
@surrim and @garvinhicking I had a look at the spartacus activity, but I did see nothing. I don't get why the plugins wouldn't show up. But I'm also not sure where to look, that side of spartacus is foreign to me. I hope that garvin can try again...

**Comment by th-h** [comment]
Spartacus - still running on PHP 5.x - fails on some new code.

We are currently migrating Spartacus and other services to a new host. I'm running some scripts by hand now, and it seems to run fine on the new host. If all goes well, the changes will show up later on.

(And if it does, I'll move the cronjobs to the new host.)

**Comment by th-h** [comment]
Okay, Spartacus is working again. New web pages and XML files have been generated and propagated.

**Pull request merged**
